### ISSUE TITLE
What do you mean about the "strange behaviour" on CUDA 11.8?

### ISSUE THREAD

**Issue by sailing-innocent** [What-a-stupid-username/MRPNN#2]
Here is my running result on Windows11, VS2022 and CUDA11.8. I am not sure if it runs as expected...
![image](https://github.com/What-a-stupid-username/MRPNN/assets/109784585/867bde37-8a80-47c3-bdec-1c6ef79e9503)

**Comment by What-a-stupid-username** [comment]
This is just what I mean by "strange behavior"...
My collaborator is still working on figuring out why.
It may be due to some bugs of the nvcc.
The predicting kernel is probably too complex and makes the compiler confused.
However, if you find the reason, please help us fix it.
At present, we can only suggest using cuda11.0-11.2 to solve this problem.

**Comment by yuchengzhong** [comment]
This issue is resolved. Now the project can be compiled in CUDA 11.8 version.
